[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "=3.2.8"

[[constraint]]
  name = "github.com/kelseyhightower/memkv"
  version = "0.1.1"

[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[override]]
  name = "google.golang.org/grpc"
  version = "=1.2.1"

[[override]]
  name = "golang.org/x/crypto"
  revision = "1351f936d976c60a0a48d728281922cf63eafb8d"

[[override]]
  name = "golang.org/x/sys"
  revision = "e48874b42435b4347fc52bdee0424a52abc974d7"

[[override]]
  name = "github.com/golang/protobuf"
  revision = "4bd1920723d7b7c925de087aa32e2187708897f7"
